Add CopyableTextField component
SYSTT/sys-monorepo pull request #132
Opened 2020-09-17 00:05 UTC by pratyushpal

## What's changed

Added a CopyableTextField which will allow users to copy their text/numerical input to their clipboard with the click of a button! 

## UI

![AddCopyableTextField](https://user-images.githubusercontent.com/20086207/93403928-d903c400-f856-11ea-846d-7c8028017f0b.gif)

## Notes
This is a WIP branch. I'm not sure what needs to be done about the styling here. Any tips/recommendations are welcome! 

This took me a while to finish but I feel a lot more confident about React and using Hooks moving forward.

2020-09-17 04:08 UTC, jtaaa commented
Love the GIF bro 😍 will check this out tomorrow!

2020-09-19 17:45 UTC, jtaaa requested changes
Yoo Pratyush this looks really good buddy. Love the hook so that we can reuse the functionality elsewhere!

There are a few changes necessary before we can get this merged in. Firstly is you need to get your editor set up with `eslint` or run `yarn lint` from the `packages/seller-client` dir. This will lint the code and make sure the formatting is consistent.

It will also show you all the `eslint` warnings and errors that your current branch has such as `typescript-eslint/no-explicit-any` which would have warned you against using the `any` type.

Next, the hook is important enough that it can be moved to its own file, possibly even moved to the utils folder. I don't consider it a part of the `CopyableTextField` component but rather an independent piece of re-useable code that is used by the `CopyableTextField`.

Finally, the `CopyableTextField` as it is right now can allow the user to copy things that they input but does not allow us to specify what is in the `MuiTextField` or stop them from overwriting it. I guess the spec could have been a bit clearer but we 100% need to be able to specific the text that will be copied when the copy icon is clicked and also optionally stop the user from being able to edit that text with a `disabled` prop.

Ideally we can take all the props that `MuiTextField` takes and spread them onto the `MuiTextField` with the extra `inputRef` and `endAdornment` props.

I've also added a bunch of comments 💬  Check them out.

Let me know if this makes sense! Thanks for help bro this actually looks good despite taking so long.

2020-09-19 17:45 UTC, jtaaa commented on packages/seller-client/src/components/CopyableTextField/CopyableTextField.stories.tsx
> +export const DummyField: React.FC = () => {
```suggestion
export const Base: React.FC = () => {
```

2020-09-19 17:45 UTC, jtaaa commented on packages/seller-client/src/components/CopyableTextField/CopyableTextField.tsx
> +       document.queryCommandSupported('copy') &&
We can remove this comment by using a self-documenting variable name like `const isCopySupported = document.queryCommandSupported('copy') ;`

2020-09-19 17:45 UTC, jtaaa commented on packages/seller-client/src/components/CopyableTextField/CopyableTextField.tsx
> +        </div>
This should be included in the [`endAdornment`](https://material-ui.com/components/text-fields/#input-adornments) on the `MuiTextField`

2020-09-19 17:45 UTC, jtaaa commented on packages/seller-client/src/components/CopyableTextField/CopyableTextField.tsx
> +      );
Lets go ahead and **throw** an error here since the ref we send to `handleCopy` should always have a `number` or `string` value. This should help us catch incorrect usage immediately.

2020-09-19 17:45 UTC, jtaaa commented on packages/seller-client/src/components/CopyableTextField/CopyableTextField.tsx
> +  const handleCopy = React.useCallback((textField: any) => {
We need to type the `textField` param. Maybe choose a better name since this hook is re-useable 💯  on any `Ref<HTMLElement>`. Maybe just `ref` or `textElementRef`.

2020-09-19 17:54 UTC, jtaaa commented
The [build](https://travis-ci.com/github/SYSTT/sys-monorepo/jobs/386021113) is also failing on Travis, seems like `handleCopy` may be typed incorrectly. The build needs to pass before we can merge. It should build in Travis if it builds locally.

2020-09-25 01:26 UTC, jtaaa commented on packages/seller-client/src/components/CopyableTextField/CopyableTextField.stories.tsx
> +};
Duplicated above

2020-09-25 01:26 UTC, jtaaa commented on packages/seller-client/src/components/CopyableTextField/CopyableTextField.tsx
> +import useCopyToClipboard from '../../utils/hooks/CopyToClipboard';
We can use absolute imports in the `seller-client` app like so
```suggestion
import useCopyToClipboard from 'utils/hooks/CopyToClipboard';
```

2020-09-25 01:26 UTC, jtaaa commented on packages/seller-client/src/components/CopyableTextField/index.ts
> +export { default } from './CopyableTextField';
You're missing a line ending here. Make sure `eslint` is auto-formatting your work on save
```suggestion
export { default } from './CopyableTextField';

```

2020-09-25 01:26 UTC, jtaaa commented on packages/seller-client/src/utils/hooks/CopyToClipboard.ts
> +    if (isCopied && resetInterval) {
This is cool that if `resetInterval` is 0 we don't reset the `isCopied` field. Was this intended behaviour? Maybe we should document this in a comment!

2020-09-25 01:26 UTC, jtaaa commented on packages/shared/src/generated/graphql.tsx
> +  String: string;
We aren't tracking generated files anymore since #135 so you can use `git rm --cache -r packages/shared/src/generated` to get rid of this guy in your branch

2020-09-25 01:26 UTC, jtaaa commented on packages/seller-client/src/utils/hooks/CopyToClipboard.ts
> +          'The type of text must be a string or number. Cannot copy otherwise.',
The caller actually doesn't know what `text` is so she'd be super surprised to see an error about the type of `text`.

A better error might be something like: `The textField ref provided is either undefined or does not contain a string or number value`

2020-09-25 01:28 UTC, jtaaa commented on packages/seller-client/src/components/CopyableTextField/CopyableTextField.tsx
> +  const handleCopy = React.useCallback((textField: any) => {
@pratyushpal how about renaming `textField` to `inputRef` or `ref` so that it's clear it is a `RefObject<HTMLInput>`

2020-09-25 03:02 UTC, pratyushpal commented on packages/seller-client/src/utils/hooks/CopyToClipboard.ts
> +    if (isCopied && resetInterval) {
yup! that was the intended behaviour

2020-09-25 04:43 UTC, pratyushpal commented on packages/seller-client/src/utils/hooks/CopyToClipboard.ts
> +    if (isCopied && resetInterval) {
Added the comment! Though it doesn't show up here as this being outdated.

2020-09-27 16:57 UTC, jtaaa approved these changes
Yoo Pratyush looking better and better!

I've added a bunch more comments. Some things are me being a bit picky with function param names, etc. Some are small improvements that aren't strictly necessary like the JSDoc stuff.

I've approved so we can get this in but please feel free to implement some of the improvements I suggest before you merge.

On top of the comments, the `CopyToClipboard` file should be renamed to `useCopyToClipboard` to match all the other hooks in the `utils/hooks` folder.

2020-09-27 16:57 UTC, jtaaa commented on packages/seller-client/src/utils/hooks/CopyToClipboard.ts
> +    (textField: RefObject<HTMLInputElement>) => {
I think my previous comment about this got lost. To me `textField` implies `MuiTextField` and it doesn't imply that it's a ref. Maybe `inputRef` is a better name.

2020-09-27 16:57 UTC, jtaaa commented on packages/seller-client/src/utils/hooks/CopyToClipboard.ts
> +      // If the resetInterval is 0 we do not reset the isCopied field
If you put this comment above the function definition as a [JSDoc comment](https://jsdoc.app/index.html) we will get this information on hover of the function name in VSCode. It's super easy to add as well. Typing `/**` above the function in vscode should add all the boilerplate stuff for you.

2020-09-27 16:57 UTC, jtaaa commented on packages/seller-client/src/components/CopyableTextField/CopyableTextField.tsx
> +  const textAreaRef = useRef<HTMLInputElement>(null);
`inputRef` instead? this isn't a `textArea`

2020-09-27 16:57 UTC, jtaaa commented on packages/seller-client/src/utils/hooks/CopyToClipboard.ts
> +    (textField: RefObject<HTMLInputElement>) => {
Don't forget to update the error message too!

2020-09-27 16:59 UTC, jtaaa commented on packages/seller-client/src/components/CopyableTextField/CopyableTextField.tsx
> +  const isCopySupported = document.queryCommandSupported('copy');
This could be returned by the `useCopyToClipboard` hook

2020-10-05 03:49 UTC, merged