Groups on ProductListItem
SYSTT/sys-monorepo pull request #64
Opened 2020-09-07 16:20 UTC by chriskrogh

## What's changed
2 have actually changed with this PR and I definitely want feedback on some of these changes.

1. I adjusted the props of this component because it seemed like we were keeping track of things that the component didn't use.
a. I adjusted the params of the `onClick` prop to not take any params instead of taking an `_id` param. The reason I did this is because we also typed `_id` as a required prop and the only place it was being used was was to call `onClick`. So since the caller will have access to `_id` and the event handler, it can just call the event handler with `_id` itself and pass that function as the `onClick` prop.
b. I removed the `_id` prop because of the above^
c. I didn't see the need for us to take in an array of images as a required prop if we only render the first image if it exists. We now take an optional image prop.
d. We don't use the `_id` field on the `image` prop so I removed it from the props type.

I also want to know what the relationship between `optionCount`, `groupNames` and `groups` is? It seems like groupNames might be redundant if we have groups, but if we don't always have groups, then we'd need `groupNames`.

2. Because of this design:
<img width="688" alt="Screen Shot 2020-09-07 at 11 11 13 AM" src="https://user-images.githubusercontent.com/35310373/92401009-d983b880-f0fa-11ea-9015-8162cf79d5d4.png">

We needed to have a way for a product to be displayed with just its name, price and groups.
With the current implementation of `ProductItemList` we couldn't achieve this because we required certain props like `status` and `optionsCount` and displayed them all the time.
To allow just groups, we need to make the other props optional and only render them if they were passed.

Also we rendered "Individual Options" when `groupNames` was falsy. But because sometimes we only want to see just name, price, orders, we needed a way to hide "Individual Options" when `groupNames` was falsy. So to render "Individual Options" we now have to pass an empty array for `groupNames`.

## UI
Everything
<img width="403" alt="Screen Shot 2020-09-07 at 11 52 30 AM" src="https://user-images.githubusercontent.com/35310373/92404107-c673e700-f100-11ea-88e0-5824029191c4.png">

____________
Just Groups
<img width="423" alt="Screen Shot 2020-09-07 at 11 52 36 AM" src="https://user-images.githubusercontent.com/35310373/92404110-c7a51400-f100-11ea-8c82-c90f117d900c.png">

____________
Status and groupNames
<img width="416" alt="Screen Shot 2020-09-07 at 11 52 42 AM" src="https://user-images.githubusercontent.com/35310373/92404112-c83daa80-f100-11ea-99d5-c03696acc16b.png">

2020-09-08 00:12 UTC, jtaaa requested changes
Absolutely love all the decisions you made 😍  10/10 for making these decisions with less than perfect knowledge of the use cases and original intention for the component.

I especially love the empty `groupNames` decision 🚀  since it matches the use cases of displaying a product vs. displaying a product option.

Just one problem with the condition on rendering `groupNames` and this is good to go!

2020-09-08 00:12 UTC, jtaaa commented on packages/seller-client/src/components/ProductListItem/ProductListItem.tsx
> +          {groupNames != null && (
JavaScript with the `!==` vs. `!=`. I think this actually works but it should really be `groupNames !== undefined` or

```suggestion
          {groupNames && (
```

2020-09-08 00:12 UTC, jtaaa commented on packages/seller-client/src/pages/ProductsPage/ProductsPage.tsx
> +            image={product.images?.[0]}
I think `product.images` will always be defined as an array so no need for the optional chaining (`?.`)

if the array is empty it will return undefined anyways for `product.images[0]`
```suggestion
            image={product.images[0]}
```

2020-09-08 00:12 UTC, jtaaa commented on packages/seller-client/src/components/ProductListItem/ProductListItem.stories.tsx
> +export const Playground: React.FC = () => {
Can we add `groups` to the Playground story? I dunno if that would be tough. Not a big deal at all.

2020-09-08 00:17 UTC, jtaaa commented
For `optionCount`, `groupNames` and `groups`:

- `optionCount` and `groupNames` only make sense if we are trying to display a `Product`
- `groups` only makes sense if we are trying to display a specific `ProductOption`

These two sets of props likely aren't going to be used together.

2020-09-08 01:13 UTC, chriskrogh commented on packages/seller-client/src/components/ProductListItem/ProductListItem.stories.tsx
> +export const Base: React.FC = () => {
Ah interesting to know!

2020-09-09 13:27 UTC, chriskrogh commented on packages/seller-client/src/components/ProductListItem/ProductListItem.tsx
> +          {groupNames != null && (
Yea `!= null` would cover the cases where it's `null` or `undefined` but you're right in the sense that `groupnames` will never be `null`. Updated the check in cff2ec8c7d46a49eff5c08106e62ea67ab17e2fe

2020-09-09 13:28 UTC, chriskrogh commented on packages/seller-client/src/components/ProductListItem/ProductListItem.stories.tsx
> +export const Playground: React.FC = () => {
Ah you're right. Updated in 43a0227ca4e4f148467cc9b61425f4da9a4922d9

2020-09-09 13:29 UTC, chriskrogh commented on packages/seller-client/src/pages/ProductsPage/ProductsPage.tsx
> +            image={product.images?.[0]}
Ah you're right. Updated in 43a0227ca4e4f148467cc9b61425f4da9a4922d9

2020-09-09 13:34 UTC, jtaaa approved these changes
Looks good!

2020-09-09 13:35 UTC, merged