Created OrderListItem component
SYSTT/sys-monorepo pull request #65
Opened 2020-09-07 19:27 UTC by chriskrogh

## What's changed
Created `OrderListItem` component.
Also created smaller sub components that are used by `OrderListItem`.
1. `DeliveryIcon` takes an `OrderStatus` and returns the corresponding delivery icon.
2. `Status` takes an `OrderStatus` and returns the status with the corresponding bdcolor.

## UI
![Screen-Recording-2020-09-07-at-3](https://user-images.githubusercontent.com/35310373/92413470-3f356c00-f11e-11ea-9901-d1e9b9efb75f.gif)

## Notes

Knobs are kool

2020-09-07 19:27 UTC, jtaaa commented
Task linked: [CU-bcghq3 Add OrderListItem component](https://app.clickup.com/t/bcghq3)

2020-09-08 01:15 UTC, jtaaa requested changes
everything LGTM except the `DeliveryIcon` component which I think should just use `order.pickup` to determine the icon.

sorry if this wasn't clear!

2020-09-08 01:15 UTC, jtaaa commented on packages/seller-client/src/components/OrderListItem/DeliveryIcon.tsx
> +const DeliveryIcon: React.FC<Props> = ({ status }) => {
The delivery icon was meant to be an indication of pickup vs delivery. Displaying the walking icon for `order.pickup === true` and the shipping icon otherwise (delivery whether custom or SYS)

2020-09-08 01:15 UTC, jtaaa commented on packages/seller-client/src/components/OrderListItem/Status.tsx
> +};
We might want to move this stuff to the theme eventually

2020-09-08 01:15 UTC, jtaaa commented on packages/seller-client/src/components/OrderListItem/Status.tsx
> +        {status.replace(/([a-z])([A-Z])/g, '$1 $2').toLocaleUpperCase()}
wais dis

Looks like you're adding spaces between camelCase words? All of the order statuses are in title case with spaces already though

2020-09-08 01:15 UTC, jtaaa commented on packages/seller-client/src/components/OrderListItem/DeliveryIcon.tsx
> +import DirectionsWalkIcon from '@material-ui/icons/DirectionsWalk';
Remember you can import both of these in one import statement

2020-09-08 01:58 UTC, jtaaa commented on packages/seller-client/src/components/OrderListItem/Status.tsx
> +        {status.replace(/([a-z])([A-Z])/g, '$1 $2').toLocaleUpperCase()}
The generated `OrderStatus` enum also lost its whitespace somewhere on the journey from the backend 😢 I guess it happens to all enums. Will check this out.

2020-09-09 14:06 UTC, chriskrogh commented on packages/seller-client/src/components/OrderListItem/DeliveryIcon.tsx
> +const DeliveryIcon: React.FC<Props> = ({ status }) => {
updated in 634b84af478bc263ed2fd862fe9a9d2f973c174d

2020-09-09 14:07 UTC, chriskrogh commented on packages/seller-client/src/components/OrderListItem/DeliveryIcon.tsx
> +import DirectionsWalkIcon from '@material-ui/icons/DirectionsWalk';
updated in 634b84af478bc263ed2fd862fe9a9d2f973c174d

2020-09-09 14:08 UTC, chriskrogh commented on packages/seller-client/src/components/OrderListItem/Status.tsx
> +        {status.replace(/([a-z])([A-Z])/g, '$1 $2').toLocaleUpperCase()}
using shared enum in 22ceb8dcfb57fd757355c9eefa43296224ab0a66

2020-09-09 14:18 UTC, jtaaa commented on packages/seller-client/src/components/OrderListItem/Status.tsx
> +        {status.replace(/([a-z])([A-Z])/g, '$1 $2').toLocaleUpperCase()}
Actually you can import straight from `generated/graphql` since we are using the shared enum in the codegen config.

2020-09-09 14:21 UTC, jtaaa approved these changes
LGTM!

2020-09-09 14:21 UTC, merged

2020-09-09 14:24 UTC, chriskrogh commented on packages/seller-client/src/components/OrderListItem/Status.tsx
> +        {status.replace(/([a-z])([A-Z])/g, '$1 $2').toLocaleUpperCase()}
oh no way! Will create a small pr to update those imports