Created BuyerDetails component
SYSTT/sys-monorepo pull request #71
Opened 2020-09-07 22:26 UTC by chriskrogh

## What's changed
Created BuyerDetails component and smaller sub components that it uses. 
(I'm a fan of splitting components when they get too big)

As of now the only optional props are the `email` and `phoneNumber` because they're also optional on the `UserModel`
`rating` doesn't exist yet, but I still built the stars logic for when it does get built.

For the stars, we can take a rating value `0<= rating <=5` and display the number of stars for that rating.

## UI
With buttons
<img width="352" alt="Screen Shot 2020-09-07 at 6 16 39 PM" src="https://user-images.githubusercontent.com/35310373/92418579-48323780-f136-11ea-8ff9-1f3a69411b85.png">
___________
Varied stars
![Screen-Recording-2020-09-07-at-6](https://user-images.githubusercontent.com/35310373/92418800-85e39000-f137-11ea-9e32-b1d813c988b1.gif)

2020-09-07 22:26 UTC, jtaaa commented
Task linked: [CU-bcgunb Add BuyerDetails component](https://app.clickup.com/t/bcgunb)

2020-09-07 22:28 UTC, chriskrogh commented on packages/seller-client/src/utils/theme.ts
> +        minWidth: 40,
Had to make this 40 so that the `email` and `phoneNumber` buttons would be circles

2020-09-08 01:51 UTC, jtaaa requested changes
The component looks really good! Initials are on point 💯 

I added quite a few comments and suggested some changes.

Most importantly, the `email` and `phoneNumber` props should be required. We display this component in the seller-client for sellers to contact buyers if necessary so it must at least show `email` (which is required on the `UserModel`). Also the user must have a `phoneNumber` set in order to make an order so at this point we are guaranteed to have the user's phoneNumber.

2020-09-08 01:51 UTC, jtaaa commented on packages/seller-client/src/components/BuyerDetails/BuyerDetails.stories.tsx
> +        )}
btw this could be a `number` knob

2020-09-08 01:51 UTC, jtaaa commented on packages/seller-client/src/components/BuyerDetails/BuyerDetails.tsx
> +import MailIcon from '@material-ui/icons/Mail';
Can use a single import

2020-09-08 01:51 UTC, jtaaa commented on packages/seller-client/src/components/BuyerDetails/BuyerDetails.tsx
> +          <Typography>
```suggestion
          <Typography variant="h6">
```

2020-09-08 01:51 UTC, jtaaa commented on packages/seller-client/src/components/BuyerDetails/BuyerDetails.tsx
> +  email?: string;
`email` is actually a required prop on the `UserModel`. In fact the `phoneNumber` prop is also required to be set before the buyer can make a purchase. Both of these props should be required

2020-09-08 01:51 UTC, jtaaa commented on packages/seller-client/src/components/BuyerDetails/RatingStars.tsx
> +        } else if (starNumber - rating < 1) {
Having the variables on the same side for each and using greater and greater than makes it easier for me to understand

```suggestion
        } else if (rating > starNumber - 1) {
```

2020-09-08 01:51 UTC, jtaaa commented on packages/seller-client/src/components/BuyerDetails/RatingStars.tsx
> +const STARS = new Array(5).fill(1);
Filling these boys with null makes it super clear that the array values aren't necessary.

I think I actually prefer using the `new Array(5).fill(null)` or `range` (from lodash) directly since `STARS` doesn't actually contain any stars. Super nit pick tho. No big deal

```suggestion
const STARS = new Array(5).fill(null);
```

2020-09-08 01:51 UTC, jtaaa commented on packages/seller-client/src/utils/theme.ts
> +        minWidth: 40,
Why not just add minWidth to the `email` and `phoneNumber` button styles?

2020-09-08 01:51 UTC, jtaaa commented on packages/seller-client/src/components/BuyerDetails/BuyerDetails.tsx
> +  address: Pick<Address, 'line1' | 'townCity' | 'country'>;
We wanna display `line2` as well if it exists

2020-09-08 01:51 UTC, jtaaa commented on packages/seller-client/src/components/BuyerDetails/BuyerDetails.tsx
> +  address: Pick<Address, 'line1' | 'townCity' | 'country'>;
and `zipCode` and `state`

2020-09-08 01:56 UTC, jtaaa commented
Also looks like our generated `ServiceArea` enum lost its white space somewhere on the journey from the backend 😢 I'll look into that

2020-09-09 15:01 UTC, chriskrogh commented on packages/seller-client/src/components/BuyerDetails/BuyerDetails.stories.tsx
> +        )}
cool! c6f7f2d58179e6f4a4b3612059170f139c853b17

2020-09-09 15:02 UTC, chriskrogh commented on packages/seller-client/src/components/BuyerDetails/BuyerDetails.tsx
> +import MailIcon from '@material-ui/icons/Mail';
updated in 10953894bd0fc2ce4482e85f95f148c73cc8fdcd

2020-09-09 15:02 UTC, chriskrogh commented on packages/seller-client/src/components/BuyerDetails/BuyerDetails.tsx
> +  email?: string;
updated in 5c8429ee1535b9946a5920d4d6f773becd81cfd1

2020-09-09 15:03 UTC, chriskrogh commented on packages/seller-client/src/components/BuyerDetails/RatingStars.tsx
> +        } else if (starNumber - rating < 1) {
updated in 8d239d83817e469e5bb88b6324a34735b74cfd55

2020-09-09 15:03 UTC, chriskrogh commented on packages/seller-client/src/components/BuyerDetails/BuyerDetails.tsx
> +  address: Pick<Address, 'line1' | 'townCity' | 'country'>;
updated in 661e46a1dd349e400070d099a1744f63098dd39a

2020-09-09 15:05 UTC, chriskrogh commented on packages/seller-client/src/utils/theme.ts
> +        minWidth: 40,
lmao🤣 idk what had me convinced that this was the only way. updated in cbd7cc9b7602b3d9b3ade18a3b271776b6cab899

2020-09-09 15:13 UTC, jtaaa approved these changes
Looks good!

2020-09-09 15:13 UTC, jtaaa commented on packages/seller-client/src/components/BuyerDetails/BuyerDetails.tsx
> +              {zipCode && zipCode}
Don't have to check for existence for these
```suggestion
              {state}
              {state && zipCode && ', '}
              {zipCode}
```

2020-09-09 18:23 UTC, merged